/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mn
 */
public class Ereignisse extends javax.swing.JDialog {

    private Chilliliste ParentForm;
    DüngerNeu DüngerForm;
    /**
     * Creates new form Eigenschaften
     */
    public Ereignisse(Chilliliste parent) {
        this.ParentForm=parent;
        setIconImage(getToolkit().getImage("Icon.png"));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPane = new javax.swing.JScrollPane();
        TblEreignisse = new javax.swing.JTable();
        TabbedPane = new javax.swing.JTabbedPane();
        PanelMessung = new javax.swing.JPanel();
        LblDateH = new javax.swing.JLabel();
        LblH = new javax.swing.JLabel();
        SpinDatMess = new javax.swing.JSpinner();
        SpinH = new javax.swing.JSpinner();
        LblCm = new javax.swing.JLabel();
        btnAddM = new javax.swing.JButton();
        PanelDünger = new javax.swing.JPanel();
        LblDateD = new javax.swing.JLabel();
        LblD = new javax.swing.JLabel();
        LblDM = new javax.swing.JLabel();
        LblCm1 = new javax.swing.JLabel();
        SpinDatDün = new javax.swing.JSpinner();
        SpinM = new javax.swing.JSpinner();
        btnAddD = new javax.swing.JButton();
        CBDünger = new javax.swing.JComboBox();
        LblInf = new javax.swing.JLabel();
        PanelBewässerung = new javax.swing.JPanel();
        LblDMB = new javax.swing.JLabel();
        LblCmB = new javax.swing.JLabel();
        SpinMB = new javax.swing.JSpinner();
        LblDateD1 = new javax.swing.JLabel();
        SpinDatDün1 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(599, 398));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        TblEreignisse.setAutoCreateRowSorter(true);
        TblEreignisse.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Datum", "Ereignis", "Dünger", "Menge in ml", "Höhe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ScrollPane.setViewportView(TblEreignisse);

        LblDateH.setText("Datum:");

        LblH.setText("Höhe:");

        SpinDatMess.setModel(new javax.swing.SpinnerDateModel());
        SpinDatMess.setEditor(new javax.swing.JSpinner.DateEditor(SpinDatMess, "dd.MM.yyyy"));

        SpinH.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 200.0d, 0.009999999776482582d));

        LblCm.setText("cm");

        btnAddM.setText("Messung hinzufügen");
        btnAddM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelMessungLayout = new javax.swing.GroupLayout(PanelMessung);
        PanelMessung.setLayout(PanelMessungLayout);
        PanelMessungLayout.setHorizontalGroup(
            PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMessungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelMessungLayout.createSequentialGroup()
                        .addGroup(PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDateH)
                            .addComponent(LblH))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpinDatMess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelMessungLayout.createSequentialGroup()
                                .addComponent(SpinH)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblCm))))
                    .addComponent(btnAddM))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        PanelMessungLayout.setVerticalGroup(
            PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMessungLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDateH)
                    .addComponent(SpinDatMess, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelMessungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblH)
                    .addComponent(SpinH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblCm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddM)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Höhen Messung", PanelMessung);

        LblDateD.setText("Datum:");

        LblD.setText("Dünger:");

        LblDM.setText("Menge:");

        LblCm1.setText("ml");

        SpinDatDün.setModel(new javax.swing.SpinnerDateModel());
        SpinDatDün.setEditor(new javax.swing.JSpinner.DateEditor(SpinDatDün, "dd.MM.yyyy"));

        SpinM.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 200.0d, 0.009999999776482582d));

        btnAddD.setText("Düngvorgang hinzufügen");
        btnAddD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDActionPerformed(evt);
            }
        });

        CBDünger.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<neu>" }));
        CBDünger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDüngerActionPerformed(evt);
            }
        });

        LblInf.setIcon(new javax.swing.ImageIcon("/home/mn/Desktop/Chilizucht/Iconinfo.png")); // NOI18N
        LblInf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LblInfMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelDüngerLayout = new javax.swing.GroupLayout(PanelDünger);
        PanelDünger.setLayout(PanelDüngerLayout);
        PanelDüngerLayout.setHorizontalGroup(
            PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDüngerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDüngerLayout.createSequentialGroup()
                        .addGroup(PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblDateD)
                            .addComponent(LblD)
                            .addComponent(LblDM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(SpinDatDün)
                            .addGroup(PanelDüngerLayout.createSequentialGroup()
                                .addComponent(SpinM, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblCm1))
                            .addComponent(CBDünger, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(3, 3, 3)
                        .addComponent(LblInf))
                    .addComponent(btnAddD))
                .addContainerGap(144, Short.MAX_VALUE))
        );
        PanelDüngerLayout.setVerticalGroup(
            PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDüngerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDateD)
                    .addComponent(SpinDatDün, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblInf)
                    .addComponent(CBDünger, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblD))
                .addGap(9, 9, 9)
                .addGroup(PanelDüngerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDM)
                    .addComponent(LblCm1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddD)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Düngvorgang", PanelDünger);

        LblDMB.setText("Menge:");

        LblCmB.setText("ml");

        SpinMB.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 200.0d, 0.009999999776482582d));

        LblDateD1.setText("Datum:");

        SpinDatDün1.setModel(new javax.swing.SpinnerDateModel());
        SpinDatDün.setEditor(new javax.swing.JSpinner.DateEditor(SpinDatDün, "dd.MM.yyyy"));

        javax.swing.GroupLayout PanelBewässerungLayout = new javax.swing.GroupLayout(PanelBewässerung);
        PanelBewässerung.setLayout(PanelBewässerungLayout);
        PanelBewässerungLayout.setHorizontalGroup(
            PanelBewässerungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBewässerungLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LblDMB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelBewässerungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBewässerungLayout.createSequentialGroup()
                        .addComponent(LblDateD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinDatDün1, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                    .addGroup(PanelBewässerungLayout.createSequentialGroup()
                        .addComponent(SpinMB, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblCmB)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelBewässerungLayout.setVerticalGroup(
            PanelBewässerungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBewässerungLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelBewässerungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDateD1)
                    .addComponent(SpinDatDün1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelBewässerungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SpinMB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblDMB)
                    .addComponent(LblCmB))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        TabbedPane.addTab("Bewässerung", PanelBewässerung);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TabbedPane)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    public boolean AskClosingforChild() // long way to keep: PRIVATE Chilliliste ParentForm; 
    {
    return this.ParentForm.AskClosing();
    }
    
   
    public void SetEditable(boolean state)
    {
    this.CBDünger.setEnabled(state);
    this.SpinDatDün.setEnabled(state);
    this.SpinDatMess.setEnabled(state);
    this.SpinH.setEnabled(state);
    this.SpinM.setEnabled(state);
    this.TabbedPane.setEnabled(state);
    this.TblEreignisse.setEnabled(state);
    this.btnAddD.setEnabled(state);
    this.btnAddM.setEnabled(state);
    }
    
    public void CleanClose()
        {
        this.dispose();
        this.ParentForm.EreignisFrame=null; // because dispose
        this.ParentForm.SetEditable(true);   
        }
       
    
    private SimpleDateFormat myformatter = new SimpleDateFormat("dd.MM.yyyy");
    
    private void btnAddMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddMActionPerformed
    DefaultTableModel deft=(DefaultTableModel)this.TblEreignisse.getModel(); 
    deft.addRow(new Object[] {myformatter.format((Date)this.SpinDatMess.getValue()),"Höhen Messung","/","/", Math.rint((double) this.SpinH.getValue()*100)/100    }); 
    }//GEN-LAST:event_btnAddMActionPerformed

    private void btnAddDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDActionPerformed
    if(this.CBDünger.getSelectedItem()!="<neu>")
        { 
        DefaultTableModel deft=(DefaultTableModel)this.TblEreignisse.getModel();
        deft.addRow(new Object[] {myformatter.format((Date)this.SpinDatDün.getValue()),"Düngevorgang",this.CBDünger.getSelectedItem(), Math.rint((double) this.SpinM.getValue()*100)/100, "/" });
        }
    else
        {
        JOptionPane.showMessageDialog(this, "<neu> ist kein gültigen Dünger", "Error", JOptionPane.ERROR_MESSAGE);
        }  
    }//GEN-LAST:event_btnAddDActionPerformed

    private void LblInfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LblInfMouseClicked
       if(this.CBDünger.getSelectedIndex()!=this.CBDünger.getItemCount()-1 && this.DüngerForm==null)
        {
        this.DüngerForm = new DüngerNeu(this);
        this.DüngerForm.SetInfoView(true);
        this.DüngerForm.setVisible(true);
        }
    }//GEN-LAST:event_LblInfMouseClicked

    private void CBDüngerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDüngerActionPerformed
   if(this.CBDünger.getSelectedIndex()==this.CBDünger.getItemCount()-1 && this.DüngerForm==null)
        {
        this.DüngerForm = new DüngerNeu(this);
        this.SetEditable(false);
        this.DüngerForm.setVisible(true);
        } 
    }//GEN-LAST:event_CBDüngerActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if(this.DüngerForm!=null)
        {
        if(this.ParentForm.showConfirmDialog("Neuer Dünger"))
            {
            this.CleanClose();
            this.DüngerForm.CleanClose();
            }
        }
    else
        {if(this.ParentForm.AskClosing()){this.CleanClose();}} 
    }//GEN-LAST:event_formWindowClosing

    public  void setDünger(String name)
    {
    this.CBDünger.insertItemAt(name, this.CBDünger.getItemCount()-1);
    this.CBDünger.setSelectedItem(name);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox CBDünger;
    private javax.swing.JLabel LblCm;
    private javax.swing.JLabel LblCm1;
    private javax.swing.JLabel LblCmB;
    private javax.swing.JLabel LblD;
    private javax.swing.JLabel LblDM;
    private javax.swing.JLabel LblDMB;
    private javax.swing.JLabel LblDateD;
    private javax.swing.JLabel LblDateD1;
    private javax.swing.JLabel LblDateH;
    private javax.swing.JLabel LblH;
    private javax.swing.JLabel LblInf;
    private javax.swing.JPanel PanelBewässerung;
    private javax.swing.JPanel PanelDünger;
    private javax.swing.JPanel PanelMessung;
    private javax.swing.JScrollPane ScrollPane;
    private javax.swing.JSpinner SpinDatDün;
    private javax.swing.JSpinner SpinDatDün1;
    private javax.swing.JSpinner SpinDatMess;
    private javax.swing.JSpinner SpinH;
    private javax.swing.JSpinner SpinM;
    private javax.swing.JSpinner SpinMB;
    private javax.swing.JTabbedPane TabbedPane;
    private javax.swing.JTable TblEreignisse;
    private javax.swing.JButton btnAddD;
    private javax.swing.JButton btnAddM;
    // End of variables declaration//GEN-END:variables

 
}
