/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB;
import DataStructur.PflanzenDatenObjekt;
import java.awt.Color;
import java.awt.Graphics;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JSpinner.DefaultEditor;

/**
 *
 * @author Wraith
 */
public final class PflanzenDaten extends javax.swing.JDialog  {
    
    public Chilliliste ParentForm;
    Object PlantID; // indicates new / info
    private SimpleDateFormat dbFormat = new SimpleDateFormat("yyyy.MM.dd");
    
    DefaultListCellRenderer renderer = new DefaultListCellRenderer()
        {
        @Override
        public void paint(Graphics g) 
            {
            setForeground(Color.BLACK);
            super.paint(g);
            }
        };
    
    /**
     * Creates new form Neu
     */
    public PflanzenDaten(Chilliliste parent, Object PlantID) throws Exception {
        setIconImage(getToolkit().getImage("Icon.png"));
        this.ParentForm=parent;
        this.PlantID=PlantID;
        initComponents();       
        loadCBboxes();
        setAttributeFields();
        this.setInfoView(true);    
        this.SetDisabledComponentsReadable();        
    }
    
    // Konstruktor für "neu"
    public PflanzenDaten(Chilliliste parent) throws Exception {
        setIconImage(getToolkit().getImage("Icon.png"));
        this.ParentForm=parent;
        initComponents();          
        this.SetDisabledComponentsReadable();
        loadCBboxes();
        this.CheckBox.setVisible(false);
        this.BtnSave.setSize(BtnSave.getSize().width, 57);
    }
    
    public ArrayList getPflanzenDatenObjekt(Object PlantID) throws Exception {
        DB con =new DB();
        return con.getPlantAttributes(PlantID);
    }
    
    public void setAttributeFields() throws Exception {
    // get Attributes from DB:
    ArrayList daten=getPflanzenDatenObjekt(PlantID);
    
    // set AttributeFields:
    this.TxtName.setText(String.valueOf(daten.get(0)));
    this.CBSorte.setSelectedItem(daten.get(1));
    this.CBArt.setSelectedItem(daten.get(2));
    this.CBTopfgröße.setSelectedItem(daten.get(3));
    this.CBHerkunft.setSelectedItem(daten.get(4));
    this.BtnColorChoose.setBackground((Color) daten.get(5));
    this.SpinScoville.setValue(daten.get(6));
    this.TxtGrad.setText(String.valueOf(daten.get(7)));
    this.SpinReifPfl.setValue(daten.get(8));
    this.SpinReifSort.setValue(daten.get(9));
    this.SpinZeit.setValue(daten.get(10));
    this.SpinReifErtragGw.setValue(daten.get(11));
    this.SpinReifErtragStk.setValue(daten.get(12));
    this.SpinDatAussaat.setValue(new SimpleDateFormat("dd.MM.yyyy").parse(String.valueOf(daten.get(13))));
    this.SpinDatAussaat.setValue(new SimpleDateFormat("dd.MM.yyyy").parse(String.valueOf(daten.get(14))));
    }
    
    public final void loadCBboxes() throws Exception
    {
    setSorteList();
    setArtList();
    setTopfgroesseList();
    setHerkunftList();    
    }
    
    public void setSorteList() throws Exception{    
    DB con= new DB();
    ArrayList names = con.getList("sorte", "tbl_sorte");
    updateCB(CBSorte, names);
    }
    
    public void setArtList() throws Exception{    
    DB con= new DB();
    ArrayList names = con.getList("art", "tbl_art");
    updateCB(CBArt, names);
    }
    
    public void setTopfgroesseList() throws Exception{    
    DB con= new DB();
    ArrayList names = con.getList("topf_gr", "tbl_pflanzen_daten");
    updateCB(CBTopfgröße, names);
    }

    public void setHerkunftList() throws Exception{    
    DB con= new DB();
    ArrayList names = con.getList("herkunft", "tbl_art");
    updateCB(CBHerkunft, names);
    }  
    
    public void updateCB(JComboBox t, ArrayList upToDate)
        {
        DefaultComboBoxModel model = (DefaultComboBoxModel) t.getModel();

        for(Object e : upToDate.toArray()){
            if(model.getIndexOf(e)==-1)
                {model.insertElementAt(e, upToDate.indexOf(e));}
            }   

    model.setSelectedItem(model.getElementAt(0));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PanNeu = new javax.swing.JPanel();
        LblInfo = new javax.swing.JLabel();
        LblInfo2 = new javax.swing.JLabel();
        BtnDel = new javax.swing.JButton();
        BtnAbbr = new javax.swing.JButton();
        BtnSave = new javax.swing.JButton();
        CheckBox = new javax.swing.JCheckBox();
        InfoPanel = new javax.swing.JPanel();
        LblName = new javax.swing.JLabel();
        LblSorte = new javax.swing.JLabel();
        LblArt = new javax.swing.JLabel();
        LblScoville = new javax.swing.JLabel();
        LblGrad = new javax.swing.JLabel();
        LblFarbe = new javax.swing.JLabel();
        LblReifPfl = new javax.swing.JLabel();
        LblReifPflTag = new javax.swing.JLabel();
        LblReifSort = new javax.swing.JLabel();
        LblReifSortTag = new javax.swing.JLabel();
        LblErtragGw = new javax.swing.JLabel();
        LblErtragStk = new javax.swing.JLabel();
        LblHerkunft = new javax.swing.JLabel();
        LblGesZeit = new javax.swing.JLabel();
        LblGesZeitTag = new javax.swing.JLabel();
        LblDatumAussaat = new javax.swing.JLabel();
        LblDatumKeimung = new javax.swing.JLabel();
        LblTopfgröße = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        SpinScoville = new javax.swing.JSpinner();
        SliderGrad = new javax.swing.JSlider();
        TxtGrad = new javax.swing.JTextField();
        SpinReifPfl = new javax.swing.JSpinner();
        SpinReifSort = new javax.swing.JSpinner();
        SpinReifErtragGw = new javax.swing.JSpinner();
        SpinReifErtragStk = new javax.swing.JSpinner();
        CBHerkunft = new javax.swing.JComboBox();
        SpinZeit = new javax.swing.JSpinner();
        BtnColorChoose = new javax.swing.JButton();
        SpinDatAussaat = new javax.swing.JSpinner();
        SpinDatKeimung = new javax.swing.JSpinner();
        CBTopfgröße = new javax.swing.JComboBox();
        CBSorte = new javax.swing.JComboBox();
        CBArt = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Zusatzinformation");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanNeu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblInfo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblInfo.setText("Bitte tragen sie alle Informationen");

        LblInfo2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblInfo2.setText("einsehen, bearbeiten und Löschen!");

        BtnDel.setText("Löschen");
        BtnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDelActionPerformed(evt);
            }
        });

        BtnAbbr.setLabel("Abbrechen");
        BtnAbbr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnAbbrMouseClicked(evt);
            }
        });
        BtnAbbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbbrActionPerformed(evt);
            }
        });

        BtnSave.setText("Speichern");
        BtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSaveActionPerformed(evt);
            }
        });

        CheckBox.setText("Bearbeiten");
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanNeuLayout = new javax.swing.GroupLayout(PanNeu);
        PanNeu.setLayout(PanNeuLayout);
        PanNeuLayout.setHorizontalGroup(
            PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanNeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(12, 12, 12)
                .addGroup(PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnDel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnAbbr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        PanNeuLayout.setVerticalGroup(
            PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanNeuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanNeuLayout.createSequentialGroup()
                        .addGroup(PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnDel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PanNeuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAbbr)
                            .addComponent(CheckBox)))
                    .addGroup(PanNeuLayout.createSequentialGroup()
                        .addComponent(LblInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblInfo2)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        InfoPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LblName.setText("Name:");

        LblSorte.setText("Sorte:");

        LblArt.setText("Art:");

        LblScoville.setText("Scoville:");

        LblGrad.setText("Schärfegrad:");

        LblFarbe.setText("Farbe:");

        LblReifPfl.setText("Reifezeit Pflanze:");

        LblReifPflTag.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblReifPflTag.setText("Tag");

        LblReifSort.setText("Reifezeit Sorte:");

        LblReifSortTag.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblReifSortTag.setText("Tag");
        LblReifSortTag.setToolTipText("");

        LblErtragGw.setText("Ertrag (Gramm):");

        LblErtragStk.setText("Ertrag (Stück):");

        LblHerkunft.setText("Herkunft:");

        LblGesZeit.setText("Gesamtzeit");

        LblGesZeitTag.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        LblGesZeitTag.setText("Tag");
        LblGesZeitTag.setToolTipText("");

        LblDatumAussaat.setText("Datum Aussaat:");

        LblDatumKeimung.setText("Datum Keimung:");

        LblTopfgröße.setText("Topfgröße:");

        SpinScoville.setModel(new javax.swing.SpinnerNumberModel(0, 0, 16000000, 1));
        SpinScoville.setName("SpinScoville"); // NOI18N

        SliderGrad.setMaximum(10);
        SliderGrad.setValue(5);

        TxtGrad.setEditable(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, SliderGrad, org.jdesktop.beansbinding.ELProperty.create("${value}"), TxtGrad, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        TxtGrad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtGradActionPerformed(evt);
            }
        });

        SpinReifPfl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 365, 1));
        SpinReifPfl.setToolTipText("");
        SpinReifPfl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinReifPflStateChanged(evt);
            }
        });

        SpinReifSort.setModel(new javax.swing.SpinnerNumberModel(1, 1, 365, 1));
        SpinReifSort.setToolTipText("");
        SpinReifSort.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpinReifSortMouseClicked(evt);
            }
        });
        SpinReifSort.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinReifSortStateChanged(evt);
            }
        });

        SpinReifErtragGw.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        SpinReifErtragGw.setToolTipText("");
        SpinReifErtragGw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpinReifErtragGwMouseClicked(evt);
            }
        });
        SpinReifErtragGw.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinReifErtragGwStateChanged(evt);
            }
        });

        SpinReifErtragStk.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10000, 1));
        SpinReifErtragStk.setToolTipText("");
        SpinReifErtragStk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpinReifErtragStkMouseClicked(evt);
            }
        });
        SpinReifErtragStk.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinReifErtragStkStateChanged(evt);
            }
        });

        CBHerkunft.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Thailand", "<neues Land>" }));
        CBHerkunft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBHerkunftActionPerformed(evt);
            }
        });

        SpinZeit.setModel(new javax.swing.SpinnerNumberModel(1, 1, 365, 1));
        SpinZeit.setToolTipText("");
        SpinZeit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SpinZeitMouseClicked(evt);
            }
        });
        SpinZeit.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinZeitStateChanged(evt);
            }
        });

        BtnColorChoose.setText(" ");
        BtnColorChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorChooseActionPerformed(evt);
            }
        });

        SpinDatAussaat.setModel(new javax.swing.SpinnerDateModel());
        SpinDatAussaat.setEditor(new javax.swing.JSpinner.DateEditor(SpinDatAussaat, "dd.MM.yyyy"));
        SpinDatAussaat.setToolTipText("");
        SpinDatAussaat.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                SpinDatAussaatStateChanged(evt);
            }
        });

        SpinDatKeimung.setModel(new javax.swing.SpinnerDateModel());
        SpinDatKeimung.setEditor(new javax.swing.JSpinner.DateEditor(SpinDatKeimung, "dd.MM.yyyy"));
        SpinDatKeimung.setToolTipText("");

        CBTopfgröße.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "groß", "klein", "mittel", "Beet", "Feld", "<Neue größe>" }));
        CBTopfgröße.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBTopfgrößeActionPerformed(evt);
            }
        });

        CBSorte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<neue Sorte>" }));
        CBSorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBSorteActionPerformed(evt);
            }
        });

        CBArt.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "<neue Art>" }));
        CBArt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBArtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout InfoPanelLayout = new javax.swing.GroupLayout(InfoPanel);
        InfoPanel.setLayout(InfoPanelLayout);
        InfoPanelLayout.setHorizontalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LblTopfgröße, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblArt)
                    .addComponent(LblSorte)
                    .addComponent(LblScoville)
                    .addComponent(LblGrad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(LblName)
                    .addComponent(LblFarbe))
                .addGap(6, 6, 6)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SpinScoville)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(SliderGrad, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtGrad))
                    .addComponent(TxtName)
                    .addComponent(BtnColorChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBTopfgröße, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBSorte, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CBArt, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblDatumKeimung, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinDatKeimung, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblDatumAussaat, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinDatAussaat, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblReifSort, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinReifSort, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblReifSortTag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblErtragGw, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinReifErtragGw, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblReifPfl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinReifPfl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblReifPflTag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblHerkunft, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CBHerkunft, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblErtragStk, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinReifErtragStk, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addComponent(LblGesZeit, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SpinZeit, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblGesZeitTag, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        InfoPanelLayout.setVerticalGroup(
            InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, InfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblName))
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(LblSorte))
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CBSorte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(LblArt)
                                    .addComponent(LblGesZeitTag)
                                    .addComponent(SpinZeit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LblGesZeit)))
                            .addGroup(InfoPanelLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CBArt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblReifPfl)
                            .addComponent(SpinReifPfl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblReifPflTag))
                        .addGap(7, 7, 7)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblReifSortTag)
                            .addComponent(SpinReifSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LblReifSort))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblErtragGw)
                            .addComponent(SpinReifErtragGw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblErtragStk)
                            .addComponent(SpinReifErtragStk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblHerkunft)
                            .addComponent(CBHerkunft, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(InfoPanelLayout.createSequentialGroup()
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblScoville)
                            .addComponent(SpinScoville, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblGrad)
                            .addComponent(SliderGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtGrad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblFarbe)
                            .addComponent(BtnColorChoose))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CBTopfgröße, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LblTopfgröße)
                    .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LblDatumAussaat)
                        .addComponent(SpinDatAussaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11)
                .addGroup(InfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDatumKeimung)
                    .addComponent(SpinDatKeimung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanNeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(InfoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SetDisabledComponentsReadable()
    {
    // ComboBoxes with own renderer: 
    this.CBArt.setRenderer(renderer);
    this.CBHerkunft.setRenderer(renderer);
    this.CBSorte.setRenderer(renderer);
    this.CBTopfgröße.setRenderer(renderer);

    //Spinner with own Method: SetSpinnerDisablesTextColor
    this.SetSpinnerDisablesTextColor(this.SpinDatAussaat, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinDatKeimung, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinReifErtragGw, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinReifErtragStk, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinReifPfl, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinReifSort, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinScoville, Color.BLACK);
    this.SetSpinnerDisablesTextColor(this.SpinZeit, Color.BLACK);
    

    }
    
    private void SetSpinnerDisablesTextColor(JSpinner spinner, Color color)
    {((DefaultEditor)spinner.getEditor()).getTextField().setDisabledTextColor(color);}
    
    public void CleanClose() // not the best way :-(
    {
    this.dispose();
    this.ParentForm.ZusatzFrame=null; // because dispose
    this.ParentForm.SetEditable(true);   
    }    
    
    private void setInfoView(boolean b)
    {       
    this.BtnSave.setEnabled(!b);
    this.BtnDel.setEnabled(!b);
    this.CBArt.setEnabled(!b);    
    this.CBHerkunft.setEnabled(!b);
    this.CBSorte.setEnabled(!b);
    this.CBTopfgröße.setEnabled(!b);
    this.SliderGrad.setEnabled(!b);
    this.SpinDatAussaat.setEnabled(!b);
    this.SpinDatKeimung.setEnabled(!b);
    this.SpinReifErtragGw.setEnabled(!b);
    this.SpinReifErtragStk.setEnabled(!b);
    this.SpinReifPfl.setEnabled(!b);
    this.SpinReifSort.setEnabled(!b);
    this.SpinScoville.setEnabled(!b);
    this.SpinZeit.setEnabled(!b);
    this.TxtGrad.setEditable(!b);
    this.TxtName.setEditable(!b);
    this.BtnColorChoose.setEnabled(!b);

    }
    
    private void BtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnSaveActionPerformed

    private void BtnAbbrMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnAbbrMouseClicked

    }//GEN-LAST:event_BtnAbbrMouseClicked

    private void BtnAbbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbbrActionPerformed
    if(this.ParentForm.AskClosing())
        {this.CleanClose();}
    }//GEN-LAST:event_BtnAbbrActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    if(this.ParentForm.AskClosing())
        {this.CleanClose();}
    }//GEN-LAST:event_formWindowClosing

    private void BtnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDelActionPerformed
    int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Alle nicht gespeicherten Einträge gehen verloren", "Warnung",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
    if(showConfirmDialog==0)
        {

        }
    
    else {}
    
    
    }//GEN-LAST:event_BtnDelActionPerformed

    private void SpinReifSortMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpinReifSortMouseClicked

    }//GEN-LAST:event_SpinReifSortMouseClicked

    private void TxtGradActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtGradActionPerformed

    }//GEN-LAST:event_TxtGradActionPerformed

    private void SpinReifPflStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinReifPflStateChanged
    if(this.SpinReifPfl.getValue()==1)
        this.LblReifPflTag.setText("Tag");
    
    else
       this.LblReifPflTag.setText("Tage"); 
    }//GEN-LAST:event_SpinReifPflStateChanged

    private void SpinReifSortStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinReifSortStateChanged
    if(this.SpinReifSort.getValue()==1)
        this.LblReifSortTag.setText("Tag");
    
    else
       this.LblReifSortTag.setText("Tage"); 
    }//GEN-LAST:event_SpinReifSortStateChanged

    private void SpinReifErtragGwMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpinReifErtragGwMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinReifErtragGwMouseClicked

    private void SpinReifErtragGwStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinReifErtragGwStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinReifErtragGwStateChanged

    private void SpinReifErtragStkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpinReifErtragStkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinReifErtragStkMouseClicked

    private void SpinReifErtragStkStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinReifErtragStkStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinReifErtragStkStateChanged

    private void CBHerkunftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBHerkunftActionPerformed
        if(this.CBHerkunft.getSelectedIndex()==this.CBHerkunft.getItemCount()-1)
            {
            String eingabe = JOptionPane.showInputDialog(this, "Bitte geben Sie den Namen eines Landes ein:", "Neues Land",JOptionPane.PLAIN_MESSAGE);
            if(eingabe!=null)
                {
                this.CBHerkunft.insertItemAt(eingabe, this.CBHerkunft.getItemCount()-1);
                this.CBHerkunft.setSelectedItem(eingabe);
                }
            else
                {this.CBHerkunft.setSelectedIndex(0);}
            }    
    }//GEN-LAST:event_CBHerkunftActionPerformed

    private void SpinZeitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SpinZeitMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_SpinZeitMouseClicked

    private void SpinZeitStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinZeitStateChanged
    if(this.SpinZeit.getValue()==1)
        this.LblGesZeitTag.setText("Tag");
    
    else
       this.LblGesZeitTag.setText("Tage"); 
    }//GEN-LAST:event_SpinZeitStateChanged

    private void BtnColorChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorChooseActionPerformed
      Color newColor = JColorChooser.showDialog(this, "Wähle Sie eine Farbe", this.BtnColorChoose.getBackground());
      this.BtnColorChoose.setBackground(newColor);
    }//GEN-LAST:event_BtnColorChooseActionPerformed

    private void SpinDatAussaatStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_SpinDatAussaatStateChanged
        this.SpinDatKeimung.setValue(this.SpinDatAussaat.getNextValue());
        this.SpinDatKeimung.setModel(new javax.swing.SpinnerDateModel((Date) this.SpinDatAussaat.getNextValue(), (Comparable) this.SpinDatAussaat.getValue(), null, java.util.Calendar.DAY_OF_MONTH));
    }//GEN-LAST:event_SpinDatAussaatStateChanged

    private void CBTopfgrößeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBTopfgrößeActionPerformed
            if(this.CBTopfgröße.getSelectedIndex()==this.CBTopfgröße.getItemCount()-1)
            {
            String eingabe = JOptionPane.showInputDialog(this, "Bitte geben Sie den Namen eines Landes ein:", "Neues Land",JOptionPane.PLAIN_MESSAGE);
            if(eingabe!=null)
                {
                this.CBTopfgröße.insertItemAt(eingabe, this.CBTopfgröße.getItemCount()-1);
                this.CBTopfgröße.setSelectedItem(eingabe);
                }
            else
                {
                this.CBTopfgröße.setSelectedIndex(0);
                }
            
            }    
    }//GEN-LAST:event_CBTopfgrößeActionPerformed

    private void CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxActionPerformed
        if(CheckBox.isSelected())
        {
            this.CheckBox.setSelected(false);
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Möchten Sie sich wirklich Einträge editieren/löschen?", "Schreibberechtigung",JOptionPane.YES_NO_OPTION ,JOptionPane.WARNING_MESSAGE);
            if(showConfirmDialog==0)
                {
                this.setInfoView(false);
                this.CheckBox.setSelected(true);
                }

            else
            {this.CheckBox.setSelected(false);}
        }

        else
        {
            this.CheckBox.setSelected(true);
            int showConfirmDialog = JOptionPane.showConfirmDialog(this, "Nicht gespeicherte Einträge werden zurückgesetzt", "Schreibberechtigung",JOptionPane.OK_CANCEL_OPTION,JOptionPane.WARNING_MESSAGE);
            if(showConfirmDialog==0)
            {
            this.setInfoView(true);
            this.CheckBox.setSelected(false);
            }

            else
            {this.CheckBox.setSelected(true);}
        }                                        
    }//GEN-LAST:event_CheckBoxActionPerformed

    private void CBSorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBSorteActionPerformed
        if(this.CBSorte.getSelectedIndex()==this.CBSorte.getItemCount()-1)
        {
        String eingabe = JOptionPane.showInputDialog(this, "Bitte geben Sie den Namen einer Sorte ein:", "Neue Sorte",JOptionPane.PLAIN_MESSAGE);
        if(eingabe!=null)
            {
            this.CBSorte.insertItemAt(eingabe, this.CBSorte.getItemCount()-1);
            this.CBSorte.setSelectedItem(eingabe);
            }
        else
            {this.CBSorte.setSelectedIndex(0);}
        } 
    }//GEN-LAST:event_CBSorteActionPerformed

    private void CBArtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBArtActionPerformed
        if(this.CBArt.getSelectedIndex()==this.CBArt.getItemCount()-1)
        {
        String eingabe = JOptionPane.showInputDialog(this, "Bitte geben Sie den Namen einer Art ein:", "Neue Art",JOptionPane.PLAIN_MESSAGE);
        if(eingabe!=null)
            {
            this.CBArt.insertItemAt(eingabe, this.CBArt.getItemCount()-1);
            this.CBArt.setSelectedItem(eingabe);
            }
        else
            {this.CBArt.setSelectedIndex(0);}
        }
    }//GEN-LAST:event_CBArtActionPerformed

    
    public void setBtnColor(Color color)
    {
    this.BtnColorChoose.setBackground(color);
    }
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbbr;
    private javax.swing.JButton BtnColorChoose;
    private javax.swing.JButton BtnDel;
    private javax.swing.JButton BtnSave;
    private javax.swing.JComboBox CBArt;
    private javax.swing.JComboBox CBHerkunft;
    private javax.swing.JComboBox CBSorte;
    private javax.swing.JComboBox CBTopfgröße;
    private javax.swing.JCheckBox CheckBox;
    private javax.swing.JPanel InfoPanel;
    private javax.swing.JLabel LblArt;
    private javax.swing.JLabel LblDatumAussaat;
    private javax.swing.JLabel LblDatumKeimung;
    private javax.swing.JLabel LblErtragGw;
    private javax.swing.JLabel LblErtragStk;
    private javax.swing.JLabel LblFarbe;
    private javax.swing.JLabel LblGesZeit;
    private javax.swing.JLabel LblGesZeitTag;
    private javax.swing.JLabel LblGrad;
    private javax.swing.JLabel LblHerkunft;
    private javax.swing.JLabel LblInfo;
    private javax.swing.JLabel LblInfo2;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblReifPfl;
    private javax.swing.JLabel LblReifPflTag;
    private javax.swing.JLabel LblReifSort;
    private javax.swing.JLabel LblReifSortTag;
    private javax.swing.JLabel LblScoville;
    private javax.swing.JLabel LblSorte;
    private javax.swing.JLabel LblTopfgröße;
    private javax.swing.JPanel PanNeu;
    private javax.swing.JSlider SliderGrad;
    private javax.swing.JSpinner SpinDatAussaat;
    private javax.swing.JSpinner SpinDatKeimung;
    private javax.swing.JSpinner SpinReifErtragGw;
    private javax.swing.JSpinner SpinReifErtragStk;
    private javax.swing.JSpinner SpinReifPfl;
    private javax.swing.JSpinner SpinReifSort;
    private javax.swing.JSpinner SpinScoville;
    private javax.swing.JSpinner SpinZeit;
    private javax.swing.JTextField TxtGrad;
    private javax.swing.JTextField TxtName;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
