/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DB.DB;
import java.awt.Color;
import java.awt.image.ImageObserver;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.security.util.Password;

/**
 *
 * @author Wraith
 */
public class Registrieren extends javax.swing.JDialog {
   
    private Einloggen parentForm;
    /**
     * Creates new form Registrieren
     */
    public Registrieren(Einloggen parent) {
    setIconImage(getToolkit().getImage("Icon.png"));
    initComponents();
    this.parentForm=parent;       
    }

    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(operation); //To change body of generated methods, choose Tools | Templates.
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanReg = new javax.swing.JPanel();
        LblInfo = new javax.swing.JLabel();
        LblPwinfo = new javax.swing.JLabel();
        PanInput = new javax.swing.JPanel();
        LblPw = new javax.swing.JLabel();
        LblSecPw = new javax.swing.JLabel();
        LblName = new javax.swing.JLabel();
        TxtName = new javax.swing.JTextField();
        TxtPw = new javax.swing.JPasswordField();
        TxtPwSec = new javax.swing.JPasswordField();
        BtnReg = new javax.swing.JButton();
        BtnAbbr = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Registrieren");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        PanReg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblInfo.setText("Bitte geben sie ihren Benutzernamen und Password ein!");

        LblPwinfo.setText("Das Password bitte zweimal!");

        PanInput.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        LblPw.setText("Passwort :");

        LblSecPw.setText("Passwort erneut eingeben :");

        LblName.setText("Name :");

        javax.swing.GroupLayout PanInputLayout = new javax.swing.GroupLayout(PanInput);
        PanInput.setLayout(PanInputLayout);
        PanInputLayout.setHorizontalGroup(
            PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LblName)
                    .addComponent(LblPw)
                    .addComponent(LblSecPw))
                .addGap(7, 7, 7)
                .addGroup(PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtPw)
                    .addComponent(TxtName)
                    .addComponent(TxtPwSec, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );
        PanInputLayout.setVerticalGroup(
            PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanInputLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblName)
                    .addComponent(TxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblPw)
                    .addComponent(TxtPw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(PanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblSecPw)
                    .addComponent(TxtPwSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        BtnReg.setText("Registrieren");
        BtnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegActionPerformed(evt);
            }
        });

        BtnAbbr.setText("Abbrechen");
        BtnAbbr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAbbrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanRegLayout = new javax.swing.GroupLayout(PanReg);
        PanReg.setLayout(PanRegLayout);
        PanRegLayout.setHorizontalGroup(
            PanRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanRegLayout.createSequentialGroup()
                .addGroup(PanRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanRegLayout.createSequentialGroup()
                        .addGroup(PanRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanRegLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(LblInfo))
                            .addGroup(PanRegLayout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addComponent(LblPwinfo)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanRegLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(PanRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(PanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanRegLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(BtnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnAbbr, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)))))
                .addContainerGap())
        );
        PanRegLayout.setVerticalGroup(
            PanRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanRegLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(LblInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LblPwinfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PanRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnAbbr, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(BtnReg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PanReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAbbrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAbbrActionPerformed
    this.dispose();
    this.parentForm.ChilliFrame=null; // Parentform has no child
    this.parentForm.Callback();
    }//GEN-LAST:event_BtnAbbrActionPerformed

    private void BtnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegActionPerformed
        boolean empty=false;
        this.LblName.setForeground(Color.black);
        this.LblPw.setForeground(Color.black);
        this.LblSecPw.setForeground(Color.black);
    
        if(this.TxtName.getText().isEmpty()) {
            this.LblName.setForeground(Color.red);
            empty=true;
        }
    
        if(this.TxtPw.getPassword().length==0) {
            this.LblPw.setForeground(Color.red);
            empty=true;
        }
 
        if(this.TxtPwSec.getPassword().length==0) {
            this.LblSecPw.setForeground(Color.red);
            empty=true;
        }    
    
        if(empty) {
            JOptionPane.showMessageDialog(this, "Bitte füllen Sie alle Felder aus", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        else{
            if(!Arrays.equals(this.TxtPwSec.getPassword(),this.TxtPw.getPassword()) && !empty) {
                JOptionPane.showMessageDialog(this, "Passwörter stimmen nicht überein", "Error", JOptionPane.ERROR_MESSAGE);
                this.LblSecPw.setForeground(Color.red);
                this.LblPw.setForeground(Color.red);
                }   
    
            else{
            String user = this.TxtName.getText();
            String md5HashedPass="";
            
            try {md5HashedPass = this.parentForm.getPasswordMd5Hash(this.TxtPwSec.getPassword());} 
            catch (Exception ex) {Logger.getLogger(Registrieren.class.getName()).log(Level.SEVERE, null, ex);}
            
            DB neuerUser = new DB();
            boolean userschonVorhanden = false;
                try {userschonVorhanden=neuerUser.UsernameExists(user);} 
                catch (Exception ex) {Logger.getLogger(Registrieren.class.getName()).log(Level.SEVERE, null, ex);}
                            
            if (!userschonVorhanden) {
                try {neuerUser.InsertIntoBenutzer(user, md5HashedPass);} 
                catch (Exception ex) {Logger.getLogger(Registrieren.class.getName()).log(Level.SEVERE, null, ex);}
                
                this.dispose();
                this.parentForm.ChilliFrame=null; // Parentform has no child
                this.parentForm.Callback();
                }
                    
                else {JOptionPane.showMessageDialog(this, "Diesen Benutzer gibt es bereits!", "Error", JOptionPane.ERROR_MESSAGE);}
            }
        }
    
    }//GEN-LAST:event_BtnRegActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    this.parentForm.clear();
    this.parentForm.ChilliFrame=null; // Parentform has no child
    this.parentForm.Callback();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAbbr;
    private javax.swing.JButton BtnReg;
    private javax.swing.JLabel LblInfo;
    private javax.swing.JLabel LblName;
    private javax.swing.JLabel LblPw;
    private javax.swing.JLabel LblPwinfo;
    private javax.swing.JLabel LblSecPw;
    private javax.swing.JPanel PanInput;
    private javax.swing.JPanel PanReg;
    private javax.swing.JTextField TxtName;
    private javax.swing.JPasswordField TxtPw;
    private javax.swing.JPasswordField TxtPwSec;
    // End of variables declaration//GEN-END:variables
}
